apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  namespace: default
  labels:
    app: trading
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
      - name: trading
        image: ghcr.io/stefanovic94/trading:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: default-env
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: trading-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: trading